stages:
  - print_message
  - deploy_prod
  - deploy_dev

deploy_prod:
  stage: deploy_prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
         echo "Deploying project to PROD server"
         npm install
         npm run build
         robocopy dist "C:\Program Files\nginx-1.25.4\html" /e

deploy_dev:
  stage: deploy_dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  script:
    echo "Deploying project to DEV server"
    npm install
    npm run build
    robocopy dist "C:\Program Files\nginx-1.25.4\html" /e

print_message:
  stage: print_message
  script:
    - echo "Deploying project..."
