stages:
  - print_message
  - build_prod

build_prod:
  stage: build_prod
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
  script:
         echo "Deploying project to PROD server"
         npm install
         npm run build
         robocopy dist "C:\Program Files\nginx-1.25.4\html" /e

print_message:
  stage: print_message
  script:
    - echo "Deploying project..."
