stages:
  - print_message
  - deploy_prod
  - deploy_dev

deploy_prod:
  stage: deploy_prod
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  script:
    - echo "Deploying project to PROD server"
    - npm install
    - npm run build
    - xcopy "dist\*" "C:\nginx\html" /y
    - echo "Finished"

deploy_dev:
  stage: deploy_dev
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  script:
    - echo "Deploying project to DEV server"
    - npm install
    - npm run build
    # - xcopy "dist\*" "C:\nginx\html" /y
    - xcopy /s /e /i "dist\*" "C:\nginx\html"
    - echo "Finished"

print_message:
  stage: print_message
  script:
    - echo "Deploying project..."
