stages:
  - print_message
  - deploy_front

deploy_front:
  stage: deploy_front
  script:
    - echo "Deploying project from %{$CI_COMMIT_BRANCH} server"
    - npm install
    - npm run build
    - xcopy /s /e /i "dist" "C:\nginx"
    - echo "Finished"

print_message:
  stage: print_message
  script:
    - echo "Deploying project..."
