stages:
  - deploy

deploy_dev:
  stage: deploy
  only:
    - main
  tags:
    - shell_dev
  script:
    - |
      echo "Deploying project from $CI_COMMIT_BRANCH server"
      npm install
      npm run build
      Remove-Item -Path "c:\nginx\html\*" -Recurse -Force
      xcopy /s /e /i "dist" "C:\nginx\html"
      echo "Finished"

deploy_prod:
  stage: deploy
  only:
    - tags
  tags:
    - shell_app
  script:
    - |
      echo "Deploying project from $CI_COMMIT_BRANCH server"
      npm install
      npm run build
      Remove-Item -Path "c:\nginx\html\*" -Recurse -Force
      xcopy /s /e /i "dist" "C:\nginx\html"
      echo "Finished"
