export const fakeOrganizationsData = [
	{
		id: 1,
		organizationTitle: "ООО “Название организации 1”",
		organizationINN: 12345678901,
		address: "656 000, г. Москва, ул. Иванова, 1В, офис 230",
		ownerName: "Иванов Иван Иванович",
		ownerINN: 12345678901,
	},
	{
		id: 2,
		organizationTitle: "ООО “Название организации 2”",
		organizationINN: 12345678902,
		address: "656 000, г. Москва, ул. Петрова, 2А, офис 345",
		ownerName: "Петров Петр Петрович",
		ownerINN: 12345678902,
	},
	{
		id: 3,
		organizationTitle: "ООО “Название организации 3”",
		organizationINN: 12345678903,
		address: "656 000, г. Москва, ул. Сидорова, 3Б, офис 456",
		ownerName: "Сидоров Сидор Сидорович",
		ownerINN: 12345678903,
	},
];

export const fakeTasksData = [
	{
		id: 1,
		date: Date.now(),
		week: "16.11-23.11",
		gtin: "GTIN",
		party: "Партия",
		type: "Отчет по выбытию ЛП",
		dateOfCreate: Date.now(),
		progress: 40,
	},
	{
		id: 2,
		date: Date.now(),
		week: "16.11-23.11",
		gtin: "GTIN",
		party: "Партия",
		type: "Отчет по выбытию ЛП",
		dateOfCreate: Date.now(),
		progress: 100,
	},
	{
		id: 3,
		date: Date.now(),
		week: "16.11-23.11",
		gtin: "GTIN",
		party: "Партия",
		type: "Отчет по выбытию ЛП",
		dateOfCreate: Date.now(),
		progress: 65,
	},
	{
		id: 4,
		date: Date.now(),
		week: "16.11-23.11",
		gtin: "GTIN",
		party: "Партия",
		type: "Отчет по выбытию ЛП",
		dateOfCreate: Date.now(),
		progress: 30,
	},
	{
		id: 5,
		date: Date.now(),
		week: "16.11-23.11",
		gtin: "GTIN",
		party: "Партия",
		type: "Отчет по выбытию ЛП",
		dateOfCreate: Date.now(),
		progress: 20,
	},
	{
		id: 6,
		date: Date.now(),
		week: "16.11-23.11",
		gtin: "GTIN",
		party: "Партия",
		type: "Отчет по выбытию ЛП",
		dateOfCreate: Date.now(),
		progress: 20,
	},
];

export const fakeUser = {
	id: 1,
	active: true,
	
}